@server_HostAddress = http://localhost:5010

### Test API Status
GET http://localhost:5010/api/status
Accept: application/json

### Login
POST http://localhost:5010/api/auth/login
Content-Type: application/json

{
  "email": "yaya@example.com",
  "motDePasse": "Yaya123!"
}

### Register
POST http://localhost:5010/api/auth/register
Content-Type: application/json

{
  "email": "titi@example.com",
  "motDePasse": "Titi123!",
  "prenom": "Titi",
  "nom": "Lkhayb",
  "gender": 0,
  "role": 4
}
